### ISSUE TITLE
Knowledge as system prompt

### ISSUE THREAD

**Issue by binarynoise** [fmaclen/hollama#100]
Currently, knowledge is passed as xml block before the first user input.
If it's not only information but instructions for the model (you are ..., pretend to be ...), it gets confused and interprets it as if I – the user – was doing these things.
When using the ollama cli and setting the knowledge as system prompt, the model behaves as expected.

The knowledge system itself is great, especially if later multiple knowledges can be passed to the model.
I'd suggest adding the possibility to set (one of) the knowledge(s) as system prompt.

**Comment by fmaclen** [comment]
I agree, this is idea makes more sense than the current XML-like implementation.

I put together a [draft PR](https://github.com/fmaclen/hollama/pull/101/files#diff-31ae89989234ded3c6f93e8e5fe7cc2c30e93536cc027383faae05989bf79205L52-L69) for this feature and deployed it here: https://knowledge-system-prompt.hollama.pages.dev/
If you can, would you test it out?

I was planning on creating a new issue to ask for help regarding prompt engineering in general.
On that note, would you be willing to provide examples of useful system prompts? 

It would give me a better idea of how the Knowledge feature is currently being used.
I personally have only used it (with mixed results) for querying documentation: 

![image](https://github.com/user-attachments/assets/85e67036-3084-49cd-9053-00edbd88f627)

**Comment by binarynoise** [comment]
I checked out your branch locally and it does not send the custom prompt at all.

One example for a system prompt is giving it a character, like 

> You are a holy llama.

 and it will share the wisdom of the Andes with us or some other role-play. One other example was making the model impersonate a fictional character by giving it the wiki article on that character.

Or more "useful": I some instructions for ChatGPT that could be imported there that don't make sense as *knowledge*:

> I am a skilled professional developer, just like you. 
I am interested in complete, unbiased, independent, absolute and universal truth.
My primary programming languages are kotlin and bash.

**Comment by fmaclen** [comment]
> I checked out your branch locally and it does not send the custom prompt at all.

Yeah, I think it does send the prompt but the models I tried sort of ignore.

Here's an example using `phi3:latest`:

![image](https://github.com/user-attachments/assets/74899ef5-c52b-4fbe-9869-5fb947ad4883)
![image](https://github.com/user-attachments/assets/4d37ee74-0605-46ca-bf0e-21b9011dc290)

I think the system prompt needs to be formatted in a specific way for it to "really stick", right now I'm just feeding the Knowledge directly.

**Comment by binarynoise** [comment]
No, I looked at the network traffic.
It does not get sent at all.

**Comment by fmaclen** [comment]
You are right, it wasn't being sent in the first prompt, but it was indeed being sent on the 2nd interaction, that's why I was seeing the correct response.

I just re-deployed a fix to that issue, however, it is now sending the system prompt _on every session message_.

Do you know if we should continuously send the same system prompt on every message or we should only limit it to the first one?

**Comment by binarynoise** [comment]
As far as I experienced it, it gets sent with every request, changing it was immediately reflected in the conversation.

**Comment by binarynoise** [comment]
Your patch works :-)

**Comment by fmaclen** [comment]
> Your patch works :-)

👌 

I haven't had time yet but I need to investigate if sending the system prompt on every message is a good idea.

**Comment by binarynoise** [comment]
I just hit the context window, it forgot who it is and then the conversation fell apart

**Comment by fmaclen** [comment]
@binarynoise just pushed another patch so the system prompt is only sent once. Give it another shot.

**Comment by binarynoise** [comment]
I don't know if it's related or not, but after some messages, I do get a lot of these and the context gets lost:

> Sorry, something went wrong.
> ```
> SyntaxError: JSON.parse: unexpected end of data at line 1 column 32762 of the JSON data
> ```

**Comment by fmaclen** [comment]
It's possible that might be a [different bug](https://github.com/fmaclen/hollama/issues/97), but I'll look into it.
