### ISSUE TITLE
Order the available models drop-down

### ISSUE THREAD

**Issue by binarynoise** [fmaclen/hollama#104]
Currently, when picking a model on the new sessions page shows the models unordered.
Sorting my name or model file size would come handy when frequently switching between different models. This would allow to quickly locate the desired model.

~~Also, the list of available models does only get updated when opening the settings page which is a bit annoying.~~
https://github.com/fmaclen/hollama/issues/105

**Comment by fmaclen** [comment]
> the list of available models does only get updated when opening the settings page

https://github.com/fmaclen/hollama/issues/105

**Comment by fmaclen** [comment]
Alphabetical order would be the easiest, but I wonder if it makes more sense to sort them by "most used"?

**Comment by binarynoise** [comment]
Most used sounds good. So the dropdown would look like this:

Empty
Most used, sorted by alphabet
Empty
All models, sorted by alphabet

But the question would be: most used all time, recently, top 3, top 10?

**Comment by binarynoise** [comment]
#120

**Comment by fmaclen** [comment]
> But the question would be: most used all time, recently, top 3, top 10?

I was thinking it'd be useful to see the last 5 recently used, but not necessarily the top 5.

I'll add a new issue for that once we merge #120, sorting alphabetically is already a huge improvement and we can punt the rest for later.
