### ISSUE TITLE
Session: add ability to edit a previously sent message by the user

### ISSUE THREAD

**Issue by fmaclen** [fmaclen/hollama#109]
REF #9 

- Any message from the `User` ~~or `Assistant`~~ will now have an edit button (next to the copy button)
- When clicking the edit button the prompt field will be populated with the content of the message
- If editing a `User` message, the `Run` button changes to `Save & Run`
- In both cases there would also be a `Cancel` (or `Dismiss`, `Discard`) button that makes everything go back to the way it was before clicking `Edit`
- We can probably use the icon: [`<Pencil />`](https://lucide.dev/icons/pencil)
- After the message has been updated run a `toast.success()` notice.

Later we can allow editing `assistant` messages:
- If editing an `Assistant` message, the `Run` button changes the label to `Save`, once clicked the new edited message should be visible in the session history.
- `Assistant` messages can only be saved because there is new completion unless the user submits a new prompt after.

**Comment by fmaclen** [comment]
@GregoMac1 I'm wondering if it makes sense to split this issue in 2 parts:
1- Edit `user` message behavior
2- Edit `assistant` message behavior

I think editing the `user` message is more useful than editing the `assistant` message, so we can punt that part for later.

**Comment by GregoMac1** [comment]
@fmaclen I was wondering on what should happen when the user edits a message and clicks `Save & Run`. Should the old response be deleted and replaced for the new response to the edited message?

**Comment by fmaclen** [comment]
> Should the old response be deleted and replaced for the new response to the edited message?

@GregoMac1 Yeah, that's what I had in mind.

**Comment by GregoMac1** [comment]
@fmaclen Great, and what should happen if there were newer messages? For example:

```
User: Prompt 1
AI: Response 1
User: Prompt 2
AI: Response 2
```

If the user edits `Prompt 1`, then `Response 1` is replaced for the new response, but should keep `Prompt 2` and `Response 2` or should we delete them as well?

I've checked ChatGPT and when you edit a message there, all next messages in the conversation are deleted.
