### ISSUE TITLE
Scrollbars in Windows don't look good in dark mode

### ISSUE THREAD

**Issue by fmaclen** [fmaclen/hollama#167]
![image](https://github.com/user-attachments/assets/e212ed7a-46c0-41a6-9cb2-a2122d65e251)

**Comment by BukuBuku11** [comment]
Hello! You can add scrollbar plugin for Tailwind using `npm install --save-dev tailwind-scrollbar` to change its colour or remove it.
[Here's the doc](https://adoxography.github.io/tailwind-scrollbar/getting-started)

**Comment by BukuBuku11** [comment]
Hello!  Scrollbar plugin for Tailwind can be used to change its colour or remove it. 
`npm install --save-dev tailwind-scrollbar`
[Here's the doc](https://adoxography.github.io/tailwind-scrollbar/getting-started)
I can send you a pr

**Comment by fmaclen** [comment]
@BukuBuku11 thanks for the suggestion, that looks good.
Yeah, if you can put up a PR that'd be greatly appreciated it!
