### ISSUE TITLE
Enable type safety in i18next

### ISSUE THREAD

**Issue by fmaclen** [fmaclen/hollama#171]
Docs: https://www.i18next.com/overview/typescript

Tasks:
- [ ] Enable typescript safety feature
- [x] Move all grouped keys to the root (i.e remove `sectionPage`, `settingsPage`, `dialog`, etc..)
- [x] Sort the keys alphabetically so it's easier to find related keys

**Comment by fmaclen** [comment]
@GregoMac1 let's prioritize this one after #170

**Comment by GregoMac1** [comment]
The second and third items of the checklist are done!

About the first one, I've been trying for some hours to make it work but I couldn't get there yet. I've followed the docs but it didn't work, and I've tried some other configurations that I've found (with no success).

I'll keep looking into it.
