### ISSUE TITLE
Ability to set parameters

### ISSUE THREAD

**Issue by iladshyan** [fmaclen/hollama#191]
It would be great if we got some ability to add some parameters. For example num_thread is an essential parameter for me as I want to use my CPU to maximum extent. I really don't know if it is even possible to set the num_thread value in current version. It takes ages to produce an output because my default thread value is 2. It would also be great if I can tweak the keep_alive parameter.

**Comment by fmaclen** [comment]
@iladshyan thanks for the request. This feature is currently planned as part of #116 with the idea that you'll be able to modify all of [these settings](https://github.com/ollama/ollama/blob/main/docs/api.md#request-7) once per **Session** or save them as a **Project** so you can re-use them.

**Comment by iladshyan** [comment]
> @iladshyan thanks for the request. This feature is currently planned as part of #116 with the idea that you'll be able to modify all of [these settings](https://github.com/ollama/ollama/blob/main/docs/api.md#request-7) once per **Session** or save them as a **Project** so you can re-use them.

That's fantastic!
