### ISSUE TITLE
Can't see button when adding large knowledge

### ISSUE THREAD

**Issue by wenrolland** [fmaclen/hollama#204]
Hi. When adding large numbers of line in the knowledge, I can't see the button at the bottom to save. I can press CTRL enter so it's ok to save but seeing the button seem like a normal UI response. 

Thanks.

![image](https://github.com/user-attachments/assets/f11fd751-5982-4953-925e-0fdd2fe1a0a5)

**Comment by fmaclen** [comment]
Thanks for reporting the issue.
Out of curiosity, what version of Hollama are you using?

**Comment by wenrolland** [comment]
Great, thanks! It was version 0.17.0. I'll check the new version!
