### ISSUE TITLE
Add German language support

### ISSUE THREAD

**Issue by jhoermann** [fmaclen/hollama#240]
I can provide a PR as native speaker.

**Comment by fmaclen** [comment]
@jhoermann appreciate your collaboration. I'm [currently working on a PR](https://github.com/fmaclen/hollama/pull/234) that will alter many of our current i18n keys, so it'd be great if you add a translation after those changes have been merged with `main`.

I'll let you know as soon as it's merged.

**Comment by jhoermann** [comment]
I’m pretty far along with the code, so I hope it’s okay @fmaclen if I go ahead and open the PR. I’ll add a comment to mention that your PR should be merged first.

**Comment by fmaclen** [comment]
Sure, go for it. No need to add a comment, I'll be the one reviewing your PR.
