### ISSUE TITLE
Model is reset after user navigates from the session

### ISSUE THREAD

**Issue by savchenko** [fmaclen/hollama#243]
Small, but annoying UX glitch. Steps to reproduce:

1. Create a chat, select model and add 1 knowledge element
2. Send arbitrary message
3. Navigate away to settings
4. Navigate back to the session
5. Observe empty model drop-down
   ![image](https://github.com/user-attachments/assets/ec29b48d-5872-4136-9837-0056d78f0107)

Might be related to https://github.com/fmaclen/hollama/issues/237

**Comment by fmaclen** [comment]
I was able to replicate the issue.
