### ISSUE TITLE
Failure to add a connection due to missing `crypto.randomUUID()`

### ISSUE THREAD

**Issue by lianggengdino** [fmaclen/hollama#244]
<img width="973" alt="image" src="https://github.com/user-attachments/assets/7d67dcc0-83c1-4bf7-9d6f-9f79d358a2c4">
When I click this button ‘add connection’, it's not pop-up window appears to add a ollama serve

**Comment by lianggengdino** [comment]
i dont know why

**Comment by fmaclen** [comment]
Can you tell me which browser/version you are using? Looks like you are missing the `crypto` dependency.

**Comment by lianggengdino** [comment]
> Can you tell me which browser/version you are using? Looks like you are missing the [`crypto`](https://caniuse.com/?search=randomUUID) dependency.

 I deploy via docker, version 0.22.0 and version 0.23.0 both have this problem, and i use chrome.

**Comment by fmaclen** [comment]
I need to know which version of Chrome you are using.

Perhaps there is something special about your browser setup that might be blocking the Crypto API, maybe a browser extension? corporate/IT-managed browser configuration?

If you can, can you try opening Inspector on any page and running:
```
console.log('crypto.randomUUID available:', !!crypto.randomUUID);
```

Should give you a result like this:
![image](https://github.com/user-attachments/assets/a09bacbd-a693-44a5-9ef1-83d8a22efdd5)

Alternative, can you try a different browser? Firefox? Safari?

**Comment by lianggengdino** [comment]
> I need to know which version of Chrome you are using.
> 
> Perhaps there is something special about your browser setup that might be blocking the Crypto API, maybe a browser extension? corporate/IT-managed browser configuration?
> 
> If you can, can you try opening Inspector on any page and running:
> 
> ```
> console.log('crypto.randomUUID available:', !!crypto.randomUUID);
> ```
> 
> Should give you a result like this: ![image](https://private-user-images.githubusercontent.com/1434675/390874589-a09bacbd-a693-44a5-9ef1-83d8a22efdd5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4NjE0NjEsIm5iZiI6MTczMjg2MTE2MSwicGF0aCI6Ii8xNDM0Njc1LzM5MDg3NDU4OS1hMDliYWNiZC1hNjkzLTQ0YTUtOWVmMS04M2Q4YTIyZWZkZDUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjlUMDYxOTIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTljZjQ3MjU5YTRlMzlmYTNhYzg5YTBhNDlmZGZiZWY1ODU5MTk1Y2Q0N2Q4ZTJmNWI3MThjMGQ2MTU1Njc0MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.VnTpS0eyatY9m326Bb8Rj3mvV4RpaR6b9P4-VoI5Wos)
> 
> Alternative, can you try a different browser? Firefox? Safari?

My chrome version is 131.0.6778.86, and i try in Safari. It has the  same problem.
<img width="1428" alt="image" src="https://github.com/user-attachments/assets/bde4b547-0b2f-4e53-8b64-0ccb05cbdfbe">

<img width="1679" alt="image" src="https://github.com/user-attachments/assets/2ba3eb8b-c5b9-4ce9-bbec-6d3c625755a3">

**Comment by fmaclen** [comment]
Understood, I'm not entirely sure why `crypto` it's not available on all of those browsers.
Regardless, I'll push a fix for this in the next few hours.
