### ISSUE TITLE
The copy button is invalid.

### ISSUE THREAD

**Issue by rankaiyx** [fmaclen/hollama#250]
version:
ghcr.io/fmaclen/hollama:latest (0.23.2)

Tested browser:
chrome
edge 
firefox

**Comment by fmaclen** [comment]
What do you mean by "is invalid"?
Are all Copy buttons not working or one in particular?

**Comment by rankaiyx** [comment]
All Copy buttons not working

**Comment by fmaclen** [comment]
Is it possible you are accessing that Docker container on an external connection over `HTTP` and not `HTTPS`?

Assuming you are on the latest version of Chrome, do you see any errors/warnings in Inspector when you click on the button?

**Comment by rankaiyx** [comment]
I'm using "OpenAI: Compatible servers (i.e. llama.cpp)"

**Comment by fmaclen** [comment]
> HTTP

That is likely the problem, browsers don't allow copy/paste functionality over HTTP (unless you are hosting the server on `localhost`). If you are hosting Hollama in an external server you must use HTTPS.

**Comment by fmaclen** [comment]
You can try creating a tunnel using HTTPS for free with [Cloudflare](https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/) or [Ngrok](https://ngrok.com/our-product/secure-tunnels).

**Comment by rankaiyx** [comment]
Okay, I'll test it. 
But it seems that HTTP just disallows reading the clipboard, not writing the clipboard.

**Comment by rankaiyx** [comment]
This is indeed the reason. After I forward the port to the local area, it will be fine.
However, it should be possible to write to the clipboard under http.

At least the following projects can implement this feature.
https://github.com/open-webui/open-webui

Maybe we can do some research about it.

**Comment by fmaclen** [comment]
Glad it worked!

> Maybe we can do some research about it.

Interesting, I just took a quick look at the way `open-webui` handles the clipboard and at a glance it looks like they are using pretty much the same logic Hollama does. Will have to take a closer look.

**Comment by rankaiyx** [comment]
The Clipboard API requires HTTPS,
The following methods should be HTTP compatible.

function copyToClipboard(text) {
  // Try to use modern Clipboard API
  if (navigator.clipboard && window.isSecureContext) {
    return navigator.clipboard.writeText(text);
  } 
  
  // Fallback to older method for compatibility
  const textArea = document.createElement('textarea');
  textArea.value = text;
  textArea.style.position = 'fixed';
  textArea.style.left = '-999999px';
  textArea.style.top = '-999999px';
  document.body.appendChild(textArea);
  textArea.focus();
  textArea.select();

  try {
    const successful = document.execCommand('copy');
    document.body.removeChild(textArea);
    return successful;
  } catch (err) {
    document.body.removeChild(textArea);
    console.error('Unable to copy', err);
    return false;
  }
}

**Comment by rankaiyx** [comment]
I'll try it, if it can be solved, maybe I can send a PR.

**Comment by rankaiyx** [comment]
Well, I don't know which files should be modified.
 I tried to modify /app/src/lib/components/ButtonCopy.svelte directly in the docker container, but it didn't seem to work.

**Comment by rankaiyx** [comment]
I noticed that open-webui considered HTTP compatibility.
Lines 225 to 265 in this file:
https://github.com/open-webui/open-webui/blob/main/src/lib/utils/index.ts

The method used by open-webui is:

export const copyToClipboard = async (text) => {
	let result = false;
	if (!navigator.clipboard) {
		const textArea = document.createElement('textarea');
		textArea.value = text;

		// Avoid scrolling to bottom
		textArea.style.top = '0';
		textArea.style.left = '0';
		textArea.style.position = 'fixed';

		document.body.appendChild(textArea);
		textArea.focus();
		textArea.select();

		try {
			const successful = document.execCommand('copy');
			const msg = successful ? 'successful' : 'unsuccessful';
			console.log('Fallback: Copying text command was ' + msg);
			result = true;
		} catch (err) {
			console.error('Fallback: Oops, unable to copy', err);
		}

		document.body.removeChild(textArea);
		return result;
	}

	result = await navigator.clipboard
		.writeText(text)
		.then(() => {
			console.log('Async: Copying to clipboard was successful!');
			return true;
		})
		.catch((error) => {
			console.error('Async: Could not copy text: ', error);
			return false;
		});

	return result;
};

**Comment by rankaiyx** [comment]
The home local area network is a common use case. In this scenario, HTTP is the easiest to deploy and sufficient.

**Comment by fmaclen** [comment]
> The home local area network is a common use case. In this scenario, HTTP is the easiest to deploy and sufficient.

I hear ya. We recently had another issue where we were using `cryptoUUID()` to generate id's but that library is also not available over HTTP.

That one wasn't too bad because we weren't using it for privacy reasons, but in this case it might become a vulnerability, in addition to `doument.executeCommand()` being flagged as deprecated which means this hack will eventually not be possible.

I'd be down to implementing the workaround as long as we alert the user that they are using the feature on an insecure context, for example:

```typescript
	function copyContent() {
		if (navigator.clipboard && window.isSecureContext) {
			navigator.clipboard.writeText(content);
		} else {
			const textArea = document.createElement('textarea');
			textArea.value = content;
			document.body.appendChild(textArea);
			textArea.select();
			try {
				document.execCommand('copy');
				toast.warning('Content copied, but your connection is not private');
			} catch (e) {
				console.error(e);
				toast.error("Couldn't copy content. Connection is not private");
			}
			document.body.removeChild(textArea);
		}
	}
```
