### ISSUE TITLE
Delete confirmation has to be clicked twice

### ISSUE THREAD

**Issue by fmaclen** [fmaclen/hollama#29]
~~It might be being fired twice.~~ Actually, pressing `ENTER` once also confirms the alert once.
[The test](https://github.com/fmaclen/hollama/commit/22adf74d5c0da17fbc94946395b5079e78013d2a#diff-b728858cc9ac6c41fb9cebc11f95efebff4b3708eefe0b569f765fee9b52998cR129) is technically also confirming the alert once so 🤷‍♂️ 

![image](https://github.com/fmaclen/hollama/assets/1434675/2c634a94-1d8a-407d-8f86-11b3335ca9f9)

**Comment by binarynoise** [comment]
I liked the way HuggingChat solved the deletion. Not easy to do on accident but easy to do on purpose.

- hover over chat in list
- trash appears
- click on trash
- trash transforms into cancel
- confirmation is to the side
- move mouse over and confirm

also allows quick bulk deleting

**Comment by fmaclen** [comment]
@binarynoise I think I understand what you described but would you mind pasting a screenshot/s of HugginFace's delete flow so I can have as a reference? I'm not familiar with it.

**Comment by binarynoise** [comment]
![grafik](https://github.com/fmaclen/hollama/assets/50302352/93168a1d-f19e-4578-85a1-806c9b2cbbe2)

![grafik](https://github.com/fmaclen/hollama/assets/50302352/25d8844f-cdae-44dd-8d2d-d4ac46c1d809)

![grafik](https://github.com/fmaclen/hollama/assets/50302352/baac232d-0bfb-4540-9b2f-7136d116d541)

![grafik](https://github.com/fmaclen/hollama/assets/50302352/52222db2-e049-4cf1-a240-26bfa4054d17)

and gone... as is my cursor in the screenshots, but I think you can still see where it hovers

**Comment by fmaclen** [comment]
I think this concept works, we should also probably replicate this behavior on the existing delete button.

If there's any chance you might be interested in submitting a PR, here's where the existing delete functionality exists:
- [`deleteSession()`](https://github.com/fmaclen/hollama/blob/main/src/routes/%5Bid%5D/%2Bpage.svelte#L55-L64)
- [Delete `<Button/>`](https://github.com/fmaclen/hollama/blob/main/src/routes/%5Bid%5D/%2Bpage.svelte#L138-L140)
- [Test](https://github.com/fmaclen/hollama/blob/main/tests/session.test.ts#L128-L145)

**Comment by binarynoise** [comment]
No, sorry, I'm not familiar with your framework

**Comment by fmaclen** [comment]
Understood, I'll try to get it out soon

**Comment by binarynoise** [comment]
Thank you. It's not urgent though, the old button just works fine enough for now

**Comment by binarynoise** [comment]
Looks and works great.
Thanks for your work!

**Comment by fmaclen** [comment]
@binarynoise Thank you for the suggestion
