### ISSUE TITLE
Please provide a docker install

### ISSUE THREAD

**Issue by arsaboo** [fmaclen/hollama#38]
It would be great if you could provide a docker installation....thanks!

**Comment by fmaclen** [comment]
I'll look into it

**Comment by fmaclen** [comment]
@arsaboo can you provide me links to other open-source projects you've used that offer a Docker installation workflow that in your experience is easy to use?

My main issue with Docker installations is that every project is totally different, some use Docker Compose, others have custom published images, others provide only a Dockerfile with a bunch of one-line commands.

I want to make sure that if we implement this it's not a bigger pain than installing Node.js locally.

**Comment by arsaboo** [comment]
Here are some projects:
1. [Open WebUI](https://github.com/open-webui/open-webui) - published images
2. [AnythingLLM](https://github.com/Mintplex-Labs/anything-llm) - published images
3. [Big-AGI](https://github.com/enricoros/big-AGI) - published images

Now, there are a few that use a dockerfile:
1. [Perplexica](https://github.com/ItzCrazyKns/Perplexica)
2. [LibreChat](https://github.com/danny-avila/LibreChat)

If possible, use an image (it is the easiest for anyone to get started).

**Comment by fmaclen** [comment]
@arsaboo thanks for the feedback.

Here are the instructions on how to create a container for the app:
https://github.com/fmaclen/hollama?tab=readme-ov-file#docker-image
