### ISSUE TITLE
Text editor grows beyond the height of it's parent

### ISSUE THREAD

**Issue by fmaclen** [fmaclen/hollama#67]
![image](https://github.com/fmaclen/hollama/assets/1434675/dbd53e04-dc52-4ed3-b178-b313a7a2bddb)

**Comment by raychz** [comment]
I see this issue as well!  The "Save" button becomes hidden after 30 or so lines of text in the editor, so the only option is the Command+Enter shortcut to submit the prompt.

**Comment by fmaclen** [comment]
@raychz You can submit with the new shortcut `Ctrl/CMD + Enter` when the button goes _out of bounds_.

**Comment by fmaclen** [comment]
@raychz just pushed a fix. Should work fine now: https://hollama.fernando.is/knowledge/xx8e38

**Comment by raychz** [comment]
Thanks @fmaclen!!  This works perfectly now.
