### ISSUE TITLE
Cannot load the UI when I completely disable internet access at the server

### ISSUE THREAD

**Issue by tihom77** [fmaclen/hollama#71]
I am trying to completely isolate the Ollama linux server from accessing outside internet and after that cannot load the Hollama UI anymore locally and remotely. Everything else in local network works as usual.

**Comment by fmaclen** [comment]
> cannot load the Hollama UI anymore locally and remotely

Is Hollama giving you an error or it simply can't connect to your Ollama server?

Are you self-hosting Hollama with Docker?
Is it on the same linux server as Ollama or some other device in your local network?

Unless the Hollama UI and Ollama are running on the same device, you'll need to set the `OLLAMA_ORIGINS` environment variable before starting the Ollama server to allow Hollama to communicate with Ollama. [Details here](https://github.com/fmaclen/hollama?tab=readme-ov-file#connecting-to-an-ollama-server).

But even if all of that is set correctly, I noticed some browser extensions (i.e. ad-blockers) preventing Hollama from connecting to Ollama.

**Comment by tihom77** [comment]
Hi,
No, I cannot open the localhost:1473 at same computer locally. It is hosted with Docker on Ubuntu. I did follow the instruction and set the OLLAMA_ORIGINS. All works when the access to outside world is enabled. When disable it and access to Holland ui stops. Strange is that I am trying with Open WebUI and works with this config. But I like more Holland and would like to use it. Thanks

**Comment by fmaclen** [comment]
> I cannot open the localhost:1473 at same computer locally

Can you double check the port you are using? It should be [`http://localhost:4173`](http://localhost:4173)
Also, just to be sure, run `docker ps -a` to check if the Hollama container is indeed running.

> I did follow the instruction and set the OLLAMA_ORIGINS

If you are running Ollama in the same device with Docker you shouldn't need to set anything in `OLLAMA_ORIGINS`

>  I did follow the instruction and set the OLLAMA_ORIGINS. All works when the access to outside world is enabled. When disable it and access to Hollama ui stops.

Not sure what you mean by "disable access to the outside world". What are you disabling exactly?

**Comment by tihom77** [comment]
Thanks a lot. It is fixed now. Was a network config error from my site. The only problem I have now is when I open it on a mobile browser. Cannot be used at all.
Appreciate your support.
