### ISSUE TITLE
Allow copying an entire session

### ISSUE THREAD

**Issue by fmaclen** [fmaclen/hollama#87]
- We already have a [`<CopyButton />`](https://github.com/fmaclen/hollama/blob/main/src/routes/sessions/%5Bid%5D/CopyButton.svelte) component.
- The content of the session can be extracted [from here](https://github.com/fmaclen/hollama/blob/main/src/routes/sessions/%5Bid%5D/%2Bpage.svelte#L39).
- We should add the new instance of `<CopyButton />` [inside this nav](https://github.com/fmaclen/hollama/blob/main/src/routes/sessions/%5Bid%5D/%2Bpage.svelte#L157-L163).

**Comment by web2ls** [comment]
I made changes
how can I add PR?

**Comment by fmaclen** [comment]
@web2ls if you forked the repository, here's a [guide to creating a PR](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork).
