### ISSUE TITLE
Add ability to retry an AI completion

### ISSUE THREAD

**Issue by fmaclen** [fmaclen/hollama#9]

**Comment by fmaclen** [comment]
@binarynoise I started working on this implementation which probably won't completely fix #103 but it will make it a lot easier to continue with the session.

I have a staging server with a draft version of this feature:
https://retry-ai-completion.hollama.pages.dev/

- You can retry any AI completion
- There may be a bug if you retry the very first completion though
- Retrying any other completion appears to work fine on my end
- This version includes the implementation for #100 

Can you try it out and let me know if you find anything odd (outside of #103)

**Comment by binarynoise** [comment]
Looks good so far, didn't encounter anything weird.

**Comment by binarynoise** [comment]
Knowledge doesn't get passed along when retrying again.

**Comment by binarynoise** [comment]
Knowledge doesn't get passed along when retrying again.

**Comment by fmaclen** [comment]
> Knowledge doesn't get passed along when retrying again.

I just pushed a fix to https://retry-ai-completion.hollama.pages.dev/
If you retry the first AI completion in a session the system prompt should be re-sent.
